architecture: minicpm
model_path: openbmb/MiniCPM-o-2_6
dataset:
  - text_dataset_path: compling/coco-val2017-obj-qa-categories
  - image_dataset_path: /path/to/your/COCO   # downloaded using configs/dataset/coco.yaml
  - text_split: val2017
  - image_split: val2017
  - prompt_column: question
  - label_column: answer
  - image_column: image_id
  - image_regex: "{id:0>12}.jpg"
forward:
  - max_new_tokens: 1
output_db: minicpm-o-coco.db
model:
  - torch_dtype: auto
  - trust_remote_code: True
  - attn_implementation: sdpa
pooled_output: True
modules:
  - llm.model.layers.13.post_attention_layernorm
  - llm.model.layers.27.post_attention_layernorm
