architecture: pixtral
model_path: mistral-community/pixtral-12b
input_dir: ./data/test-images/
prompt: "Describe the color in this image in one word."
output_db: output/Pixtral-12B-2409.db
modules:
  - model.language_model.layers.19.input_layernorm
  - model.language_model.layers.39.input_layernorm
