architecture: qwen
model_path: /model-weights/Qwen2-VL-7B-Instruct
dataset:
  - text_dataset_path: compling/CLEVR_val_categories
  - image_dataset_path: /scratch/ssd004/scratch/hsheta/datasets/CLEVR_v1.0/images  # downloaded using configs/dataset/clevr.yaml
  - text_split: color
  - image_split: val
  - prompt_column: Q
  - label_column: A
  - image_column: image_filename
output_db: /projects/compling/hsheta/qwen_color.db
pooled_output: True
modules:
  - model.layers.13.post_attention_layernorm
  - model.layers.27.post_attention_layernorm
