architecture: dino
model_path: facebook/dinov2-base
model:
  - torch_dtype: auto
output_db: output/dinov2.db
input_dir: ./data/test-images/
prompt: "Describe the color in this image in one word."
modules:
  - encoder.layer.5.layer_scale2
  - encoder.layer.10.layer_scale2
