dataset_path: wonderwind271/CLEVR_val
split_name: val
parent_folder: CLEVR
dataset_download_place: data/CLEVR/CLEVR_dataset
img_url: https://dl.fbaipublicfiles.com/clevr/CLEVR_v1.0.zip
img_download_place: data/CLEVR/CLEVR_v1.0.zip
