
text_dataset_path: compling/coco-val2017-obj-qa-categories
image_dataset_path: /scratch/ssd004/scratch/hsheta/datasets/COCO  # downloaded using configs/dataset/coco.yaml
text_split: val2017
image_split: val2017
prompt_column: question
label_column: answer
image_column: image_id
image_regex: "{id:0>12}.jpg"
save_path: data/COCO/mapped
