
text_dataset_path: compling/GQA_dataset_binary
image_dataset_path: /scratch/ssd004/scratch/hsheta/datasets/GQA/images  # downloaded using configs/dataset/gqa.yaml
text_split: val
# image_split: val
prompt_column: question
label_column: answer
image_column: id
image_regex: "{id}.jpg"
save_path: data/GQA/mapped
