architecture: blip2
model_path: Salesforce/blip2-opt-2.7b
dataset:
  - text_dataset_path: compling/coco-val2017-obj-qa-categories
  - image_dataset_path: /path/to/COCO/images  # downloaded using configs/dataset/coco.yaml
  - text_split: val2017
  - image_split: val2017
  - prompt_column: question
  - label_column: answer
  - image_column: image_id
  - image_regex: "{id:0>12}.jpg"
output_db: blip2_coco.db
pooled_output: True
modules:
  - language_model.model.decoder.layers.16.self_attn_layer_norm
  - language_model.model.decoder.layers.31.self_attn_layer_norm
