architecture: llava
model_path: llava-hf/llava-1.5-7b-hf
dataset:
  - text_dataset_path: compling/coco-val2017-obj-qa-categories
  - image_dataset_path: /path/to/COCO  # downloaded using configs/dataset/coco.yaml
  - text_split: val2017
  - image_split: val2017
  - prompt_column: question
  - label_column: answer
  - image_column: image_id
  - image_regex: "{id:0>12}.jpg"
output_db: llava_coco.db
pooled_output: True
modules:
  - language_model.model.layers.16.post_attention_layernorm
  - language_model.model.layers.31.post_attention_layernorm
