architecture: aya-vision
model_path: CohereLabs/aya-vision-8b
model:
  - torch_dtype: float16
output_db: output/aya-vision.db
input_dir: ./data/
prompt: "Describe the color in this image in one word."
modules:
  - language_model.model.layers.15.input_layernorm
  - language_model.model.layers.31.input_layernorm
