architecture: janus
model_path: deepseek-ai/JanusFlow-1.3B
model:
  - torch_dtype: auto
output_db: janus1d3b.db
input_dir: ../data
prompt: "Describe the color in this image in one word."
modules:
  - vision_und_enc_model.vision_tower.blocks.5.attn.k_norm
  - language_model.model.layers.14.self_attn
