architecture: minicpm
model_path: compling/MiniCPM-V-2
model:
  - torch_dtype: auto
  - trust_remote_code: True
forward:
  - max_new_tokens: 1
output_db: output/minicpm.db
input_dir: ./data/
prompt: "Describe the color in this image in one word."
modules:
  - llm.lm_head
  - vpm.encoder.layers.26
