architecture: perception-lm
model_path: facebook/Perception-LM-1B
model:
  - token: <HUGGINGFACE_TOKEN>
output_db: perception_lm.db
input_dir: ./data
prompt: "Describe the color in this image in one word."
modules:
  - model.language_model.layers.15.post_attention_layernorm
