architecture: qwen
model_path: Qwen/Qwen2-VL-2B-Instruct
model:
  - torch_dtype: auto
output_dir: ./output_dir/
input_dir: ./data/
text_input:
  - description_prompt:
    - prompt: "Describe the color in this image."
    - filter: black.*
  - one_word_prompt:
    - prompt: "Describe the color in this image in one word."
    - filter: red.*

modules:
  - lm_head
  - visual.blocks.31
