architecture: llava
model_path: llava-hf/llava-1.5-7b-hf
dataset:
  - text_dataset_path: compling/CLEVR_val_categories
  - image_dataset_path: /path/to/CLEVR_v1.0/images  # downloaded using configs/dataset/clevr.yaml
  - text_split: number
  - image_split: val
  - prompt_column: Q
  - label_column: A
  - image_column: image_filename
output_db: llava_number.db
pooled_output: True
modules:
  - language_model.model.layers.16.post_attention_layernorm
  - language_model.model.layers.31.post_attention_layernorm
