architecture: qwen
model_path: /model-weights/Qwen2-VL-7B-Instruct
dataset:
  - text_dataset_path: compling/GQA_dataset_binary
  - image_dataset_path: /scratch/ssd004/scratch/hsheta/datasets/GQA/images  # downloaded using configs/dataset/gqa.yaml
  - text_split: val
  - prompt_column: question
  - label_column: answer
  - image_column: id
  - image_regex: "{id}.jpg"
output_db: /projects/compling/hsheta/qwen_gqa.db
pooled_output: True
modules:
  - model.layers.13.post_attention_layernorm
  - model.layers.27.post_attention_layernorm
